import { invoke } from '@tauri-apps/api/core';

export interface TaskTag {
  name: string;
  tag_fg: string | null;
  tag_bg: string | null;
}

export interface Task {
  id: string;
  name: string;
  status: { status: string; color: string | null };
  priority: { id: string | null; priority: string | null; color: string | null } | null;
  time_estimate: number | null;
  url: string | null;
  due_date: string | null;
  tags: TaskTag[];
}

export interface NowNextResult {
  now: Task | null;
  next: Task[];
}

// Lists are loaded at app startup from `os-config.json` (generated by
// `python scripts/setup.py`). The frontend reads them via the config store.
// See `src/lib/stores/config.ts`.
export interface ListEntry { id: string; label: string; slug: string | null }
export type ListId = string;

export const PRIORITY_META: Record<string, { label: string; color: string }> = {
  '1': { label: 'Urgent', color: '#ef4444' },
  '2': { label: 'High',   color: '#f97316' },
  '3': { label: 'Normal', color: '#3b82f6' },
  '4': { label: 'Low',    color: '#6b7280' },
};

export const getTodayTasks = () => invoke<Task[]>('get_today_tasks');
export const getCompletedTodayTasks = () => invoke<Task[]>('get_completed_today_tasks');
export const getNowNext    = (preserveNow: boolean) =>
  invoke<NowNextResult>('get_now_next', { preserveNow });
export const completeTask  = (taskId: string, taskName: string, tags: TaskTag[]) =>
  invoke<void>('complete_task', { taskId, taskName, tags });
export const uncheckTask   = (taskId: string, taskName: string, tags: TaskTag[]) =>
  invoke<void>('uncheck_task', { taskId, taskName, tags });
export const createTask    = (name: string, listId: string, priority: number, tags: string[]) =>
  invoke<Task>('create_task', { name, listId, priority, tags });
export const deleteTask    = (taskId: string, taskName: string, tags: TaskTag[]) =>
  invoke<void>('delete_task', { taskId, taskName, tags });
export const updateTask    = (
  taskId: string, taskName: string, tags: TaskTag[],
  newName?: string,
  newPriority?: number,
  newDueDate?: number,      // ms timestamp; 0 = clear; omit = no change
  newTimeEstimate?: number, // ms; 0 = clear; omit = no change
  details?: string,
) => invoke<void>('update_task', { taskId, taskName, tags, newName, newPriority, newDueDate, newTimeEstimate, details });
export const ensureLogDoc  = () =>
  invoke<void>('ensure_log_doc');

export const startDay = () => invoke<string>('start_day');

export interface StatEntry {
  date: string;   // YYYY-MM-DD
  count: number;
}
export const getTaskStats = () => invoke<StatEntry[]>('get_task_stats');
